stages:
  - push image

docker build:
  image: docker:18.09.9-git
  stage: push image
  only:
    - tags
  before_script:
    - apk add gettext
    - envsubst < Dockerfile_template > Dockerfile
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG $EXTRA_TAGS .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

