before_script:
  - echo "machine gitlab.quintagroup.com login gitlab+deploy-token-32 password $D_TOKEN" > ~/.netrc
  - pip install -r requirements-dev.txt
  - pip install -e .

stages:
  - test

test_sanbox_true:
  image: python:2.7
  stage: test
  tags:
    - dind
  variables:
    SANDBOX_MODE: 'True'
    GIT_STRATEGY: clone
  script:
    - pytest openprocurement/bridge/pricequotation/tests/ --cov=openprocurement/bridge/pricequotation


test_sanbox_false:
  image: python:2.7
  stage: test
  variables:
    GIT_STRATEGY: clone
  tags:
    - dind
  script:
    - pytest openprocurement/bridge/pricequotation/tests/ --cov=openprocurement/bridge/pricequotation
