FROM prozorro/base

COPY requirements /app/requirements

WORKDIR /app
RUN virtualenv --clear --never-download . && ./bin/pip install --upgrade pip && ./bin/pip install -r requirements/base.txt

COPY src /app/src
RUN ./bin/pip install -r requirements/app.txt

CMD ["bin/databridge", "etc/pq_data_bridge.yaml"]
