FROM prozorro/base

WORKDIR /app

COPY . /app

RUN pip install --upgrade pip && pip install -r requirements-dev.txt
RUN pip install -e .
RUN ls -lah
RUN apt-get clean

CMD ["bin/databridge", "etc/pq_data_bridge.yaml"]
